name: Aera Workflow Scheduler

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    environment: Aera_Workflows


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --ignore-scripts

      # 1. Update Playwright to the latest version to ensure Ubuntu 24.04 support
      - name: Update Playwright
        run: npm install @playwright/test@latest

      # 2. Use the official CLI to install Chromium and its system dependencies
      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium


      - name: Run workflow scheduler
        run: node cron-runner.js
        # env:
        #   SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        #   SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
